/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './index';
class SlimScrollModuleInjector extends import0.ɵNgModuleInjector<import1.SlimScrollModule> {
  _SlimScrollModule_0:import1.SlimScrollModule;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  createInternal():import1.SlimScrollModule {
    this._SlimScrollModule_0 = new import1.SlimScrollModule();
    return this._SlimScrollModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.SlimScrollModule)) { return this._SlimScrollModule_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const SlimScrollModuleNgFactory:import0.NgModuleFactory<import1.SlimScrollModule> = new import0.NgModuleFactory<any>(SlimScrollModuleInjector,import1.SlimScrollModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvUEM2L1NvdXJjZS9SZXBvcy9uZzItc2xpbXNjcm9sbC9pbmRleC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9QQzYvU291cmNlL1JlcG9zL25nMi1zbGltc2Nyb2xsL2luZGV4LnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
